<?php
/**
 * @file
 * Module file for the Emmet module, which adds Emmet TextArea Library.
 */

/**
 * Implements hook_libraries_info().
 */
function emmet_libraries_info() {

  $libraries['emmet'] = array(
    'name' => 'Emmet Plugin for textarea fields',
    'vendor url' => 'https://github.com/emmetio/textarea',
    'download url' => 'https://github.com/emmetio/textarea/archive/master.zip',
    'version arguments' => array(
      'file' => 'emmet.js',
      'pattern' => "@VERSION = '([0-9a-zA-Z\.-]+)'@",
      'lines' => 65,
    ),
    'files' => array(
      'js' => array('emmet.min.js'),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_permission().
 */
function emmet_permission() {
  return array(
    'use emmet' => array(
      'title' => t('Use Emmet'),
      'description' => t('Use Emmet Toolkit in textareas.'),
    ),
    'administer emmet module' => array(
      'title' => t('Administer Emmet Module'),
      'description' => t('Change Emmet settings.'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function emmet_form_alter(&$form, &$form_state, $form_id) {
  if (user_access('use emmet')) {
    $form['emmet']['#attached']['libraries_load'][] = array('emmet');
  }
}

/**
 * Implements hook_page_build().
 */
function emmet_page_build(&$page) {
  if (user_access('use emmet')) {

    $page['page_bottom']['emmet'] = array(
      '#markup' => t("<script>
// debugging on Chrome
if (typeof _ != 'undefined') {
    emmet.require('textarea').setup({
    pretty_break: true, // enable formatted line breaks (when inserting
                        // between opening and closing tag)
    use_tab: true       // expand abbreviations by Tab key
    });
    }
</script>
<noscript>
<p>Emmet Development Tool not enabled on this page.</p>
</noscript>"),
    );
  }
}

/**
 * Implements hook_menu().
 */
function emmet_menu() {
 $items['admin/config/development/emmet'] = array(
    'title' => 'Emmet Settings',
    'description' => 'Emmet module configuration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('emmet_settings_callback'),
    'access arguments' => array('administer emmet module'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Emmet settings callback.
 */
function emmet_settings_callback() {
  $trigger = variable_get('emmet_trigger');
  $form['emmet_trigger'] = array(
    '#type' => 'radios',
    '#title' => t('Emmet Trigger Key'),
    '#default_value' => $trigger,
    '#options' => array(
      'tab' => t('Tab'),
      'return' => t('Return')
      ),
    '#description' => t(
      'Select the Emmet trigger key you want to use.'),
  );
  return system_settings_form($form);
}
